package proyecto1;

import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    //Atributos 
    
    //metodo constructor 
    
    //metodos 
    
    
    // se le pasa el arreglo de clientes para poder utilizarlos en esta ventana
    Clientes[] persona = new Clientes[5];

    public Login(Clientes[] pers) {
        initComponents();
        this.persona = pers;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btmInicioSesion = new javax.swing.JButton();
        btmRegresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Password:");

        btmInicioSesion.setBackground(new java.awt.Color(102, 255, 102));
        btmInicioSesion.setText("Iniciar Sesion");
        btmInicioSesion.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btmInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmInicioSesionActionPerformed(evt);
            }
        });

        btmRegresar1.setBackground(new java.awt.Color(153, 153, 153));
        btmRegresar1.setText("Regresar");
        btmRegresar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btmRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRegresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btmInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRegresar1ActionPerformed
        // limpiar los textField
        try {
            txtUsuario.setText(null);
            txtPassword.setText(null);

            //volver a la ventana inicio
            HomePage ventanaInicio = new HomePage();
            ventanaInicio.setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "¡Compruebe que esta ingresando la informacion como se indica en el manual de usuario!");
        }


    }//GEN-LAST:event_btmRegresar1ActionPerformed

    private void btmInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmInicioSesionActionPerformed
        //condicionales para validar contrasena
        String user = txtUsuario.getText();
        String pass = txtPassword.getText();
        if (!txtUsuario.getText().isEmpty() && !txtPassword.getText().isEmpty()) {
            
            if (user.equals("administrador") && pass.equals("202106003")) {
                MenuPrincipal1 menu = new MenuPrincipal1(persona);
                menu.setVisible(true);
                this.dispose();

            } else {
                try {
                    txtUsuario.setText("");
                    txtPassword.setText("");
                    JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectas");
                } catch (Exception ex) {

                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "¡Debe rellenar todos los campos!");
        }
    }//GEN-LAST:event_btmInicioSesionActionPerformed
 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmInicioSesion;
    private javax.swing.JButton btmRegresar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
