package proyecto1;

public class MenuPrincipal1 extends javax.swing.JFrame {

      //crear arreglo para llevar informacion en esta ventana
    Clientes[] personas = new Clientes[5];

    public MenuPrincipal1(Clientes[] persona) { // recibir informacion de la ventana anterior
        initComponents();
        this.personas = persona; //asignar la info de otra pagina a pagina actual

    }

    public MenuPrincipal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistra = new javax.swing.JMenu();
        menuCrear = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenu();
        menuDeposito = new javax.swing.JMenu();
        menuTransferencia = new javax.swing.JMenu();
        menuPagoServicio = new javax.swing.JMenu();
        menuHistorial = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 0, 0));
        escritorio.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1204, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        menuRegistra.setText("Registrar Clientes");
        menuRegistra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegistraMouseClicked(evt);
            }
        });
        menuRegistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistraActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuRegistra);

        menuCrear.setText("Crear Cuenta");
        menuCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCrearMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCrear);

        menuInfo.setText("Informacion Clientes");
        menuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInfoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInfo);

        menuDeposito.setText("Deposito");
        menuDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDepositoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDeposito);

        menuTransferencia.setText("Transferencia");
        menuTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTransferenciaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuTransferencia);

        menuPagoServicio.setText("Pago Servicio");
        menuPagoServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPagoServicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPagoServicio);

        menuHistorial.setText("Historial Transferencia");
        menuHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHistorialMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuHistorial);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRegistraActionPerformed

    private void menuRegistraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistraMouseClicked

        CrearClientes ventanaCliente = new CrearClientes(personas);
        escritorio.add(ventanaCliente);
        ventanaCliente.setVisible(true);
        
    }//GEN-LAST:event_menuRegistraMouseClicked

    private void menuCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCrearMouseClicked

        CrearCuentas ventanaCuenta = new CrearCuentas(personas);
        escritorio.add(ventanaCuenta);
        ventanaCuenta.setVisible(true);

    }//GEN-LAST:event_menuCrearMouseClicked

    private void menuInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInfoMouseClicked
        
        InformacionClientes ventanaInformacion = new InformacionClientes(personas);
        escritorio.add(ventanaInformacion);
        ventanaInformacion.setVisible(true);
        
    }//GEN-LAST:event_menuInfoMouseClicked

    private void menuDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDepositoMouseClicked
       
        VDepositos ventanaDepositos = new VDepositos(personas);
        escritorio.add(ventanaDepositos);
        ventanaDepositos.setVisible(true);
        
    }//GEN-LAST:event_menuDepositoMouseClicked

    private void menuTransferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransferenciaMouseClicked
       
        VTransferencias ventanaTransferencia = new VTransferencias(personas);
        escritorio.add(ventanaTransferencia);
        ventanaTransferencia.setVisible(true);
        
    }//GEN-LAST:event_menuTransferenciaMouseClicked

    private void menuPagoServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPagoServicioMouseClicked
       
        VPagoServicio ventanaPago = new VPagoServicio(personas);
        escritorio.add(ventanaPago);
        ventanaPago.setVisible(true);

    }//GEN-LAST:event_menuPagoServicioMouseClicked

    private void menuHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHistorialMouseClicked
        
        VHistorial ventanaHistorial = new VHistorial(personas);
        escritorio.add(ventanaHistorial);
        ventanaHistorial.setVisible(true);
        
    }//GEN-LAST:event_menuHistorialMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCrear;
    private javax.swing.JMenu menuDeposito;
    private javax.swing.JMenu menuHistorial;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuPagoServicio;
    private javax.swing.JMenu menuRegistra;
    private javax.swing.JMenu menuTransferencia;
    // End of variables declaration//GEN-END:variables
}
