package com.mycompany.taller3;

public class MenuPrincipal extends javax.swing.JFrame {
    //atributos 
    
    //metodo constructor
    
    //metodos
    Clientes[] personas = new Clientes[5];
    
    public MenuPrincipal() {
        initComponents();
        
        //inicializacion de objetos 
        for (int i = 0; i < 5; i++) {
            personas[i] = new Clientes();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        RegistraClientes = new javax.swing.JMenu();
        menuCrear = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenu();
        Deposito = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 0, 0));
        escritorio.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        RegistraClientes.setText("RegistrarClientes");
        RegistraClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistraClientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(RegistraClientes);

        menuCrear.setText("Crear Cuenta");
        menuCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCrearMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCrear);

        menuInfo.setText("InformacionClientes");
        menuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInfoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInfo);

        Deposito.setText("Deposito");
        jMenuBar1.add(Deposito);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistraClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistraClientesMouseClicked
          CrearClientes ventanaIngreso = new CrearClientes(personas);
          escritorio.add(ventanaIngreso);
          ventanaIngreso.setVisible(true);
//        CrearClientes ventanaIngreso = new CrearClientes();
//        escritorio.add(ventanaIngreso);
//        ventanaIngreso.setVisible(true);
    }//GEN-LAST:event_RegistraClientesMouseClicked

    private void menuCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCrearMouseClicked
        CrearCuentas ventanaCuenta = new CrearCuentas(personas);
        escritorio.add(ventanaCuenta);
        ventanaCuenta.setVisible(true);
    }//GEN-LAST:event_menuCrearMouseClicked

    private void menuInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInfoMouseClicked
        InformacionClientes ventanaInformacion = new InformacionClientes();
        escritorio.add( ventanaInformacion);
        ventanaInformacion.setVisible(true);
    }//GEN-LAST:event_menuInfoMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Deposito;
    private javax.swing.JMenu RegistraClientes;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCrear;
    private javax.swing.JMenu menuInfo;
    // End of variables declaration//GEN-END:variables
}
